apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-api
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: sample-api
          resources:
            requests:
              cpu: 200m
              memory: 10Mi
            limits:
              cpu: 1
              memory: 20Mi