apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datadog-agent
  namespace: argocd
spec:
  project: default
  source: 
    repoURL: https://github.com/tomoyasuzuki/kube-sample
    targetRevision: HEAD
    path: ./addons/datadog/template
  destination:
    server: https://kubernetes.default.svc
    namespace: datadog
  syncPolicy:
    automated: {}