apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: descheduler
  namespace: argocd
spec:
  project: default
  source: 
    repoURL: https://github.com/tomoyasuzuki/kube-sample
    targetRevision: HEAD
    path: ./addons/descheduler/template
  destination:
    server: https://kubernetes.default.svc
    namespace: descheduler
  syncPolicy:
    automated: {}