apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
spec:
  project: default
  source: 
    repoURL: https://github.com/tomoyasuzuki/kube-sample
    targetRevision: HEAD
    path: ./addons/argocd/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: {}