apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  repositories: |
    - url: https://github.com/tomoyasuzuki/kube-sample
    - url: https://github.com/tomoyasuzuki/sample-api
  repository.credentials: |
    - url: https://github.com/tomoyasuzuki
      passwordSecret:
        name: repo-secret
        key: password
      usernameSecret:
        name: repo-secret
        key: username
  
