apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-api
spec:
  template:
    spec:
      topologySpreadConstraints:
      - maxSkew: 3
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
      - maxSkew: 5
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
      containers:
        - image: <your-image>
          name: sample-api
          ports: 
          - containerPort: 80
      
      